# Generated by Django 5.1.5 on 2025-01-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnoseReport',
            fields=[
                ('diagnose_ID', models.AutoField(primary_key=True, serialize=False)),
                ('diagnose_result', models.BooleanField()),
                ('confidence', models.FloatField()),
                ('camera_type', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-binary', 'Non Binary')], max_length=10)),
                ('diabetes_history', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], max_length=10)),
                ('family_diabetes_history', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], max_length=10)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
    ]
