# Generated by Django 5.1.5 on 2025-01-24 19:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeye', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosereport',
            name='fundus_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='fundus_images/'),
            preserve_default=False,
        ),
    ]
